### ISSUE TITLE
Typesetting math in defblocks

### ISSUE THREAD

**Issue by Nidish96** [alhassy/org-special-block-extras#10]
Firstly great package, thanks a lot!!

While typesetting inline math on org, I usually just use $<equation>$ and proceed, and the latex interpreter interprets it as latex math and the html interpreter does the right thing too. 

But the following doesn't work:

> `#+begin_details SDOF equations are $m\ddot{x}=f(t)$`
> `The above is a differential equation with $\ddot{x}$.`
> `#+end_details`

Here's the result to this on html :
![image](https://user-images.githubusercontent.com/17080531/118328477-98367a80-b4cb-11eb-9a74-3e8bc240b9cd.png)

On pdflatex :
![image](https://user-images.githubusercontent.com/17080531/118328721-adaba480-b4cb-11eb-9770-2efc3e90531f.png)

As you can see, the second math equation works properly, but the first one doesn't.

Is there any easy way to fix this?

**Comment by Nidish96** [comment]
Update: delimiting the `$`s and `/`s I could get the above to work with latex but not with html:

`SDOF equations are \$m\\ddot{x}=f(t)\$` yields what is expected on latex.

**Comment by alhassy** [comment]
I'm glad you like the package ❤️ 

The way that the special blocks work is that their main argument is actually a string literal; it is **not** generally interpreted as Org markup. As such, if we treat it as a string then we just need to escape the relevant parts:
```
#+begin_details "SDOF equations are \\(m\\ddot{x}=f(t)\\)"
The above is a differential equation with $\ddot{x}$.
#+end_details
```

This works and produces, in HTML:
<img width="378" alt="Screen Shot 2021-08-04 at 11 21 44 PM" src="https://user-images.githubusercontent.com/28608756/128285887-844d358d-b003-4c16-a26f-ad3343555d76.png">

It seems that the above string fact should be better documented. Sorry about that 😅

**Comment by Nidish96** [comment]
Thanks for the response (apologies for my delay). 

I can confirm that your solution works. 
But I found it interesting that the following works,
``` 
#+begin_details "SDOF equations are \\(m\\ddot{x}=f(t)\\)"
The above is a differential equation with $\ddot{x}$.
#+end_details
 ``` 
but this does not:
``` 
#+begin_details "SDOF equations are \$m\\ddot{x}=f(t)\$"
The above is a differential equation with $\ddot{x}$.
#+end_details
 ``` 
Output of the second version is:
![image](https://user-images.githubusercontent.com/17080531/226987232-714e5526-6f48-4183-bd64-dd67ef77c963.png)

This might just be a minor point, since latex supports both ```$ eqn $``` as well as ```\( eqn \)``` for inline math, but i was just curious if there was any particular reason for this.

**Comment by alhassy** [comment]
>  but i was just curious if there was any particular reason for this.

@Nidish96 This is because Org needs to see some top-level math before loading MathJax ---see Issue #17 for a MWE Org file that mentions this issue and [demonstrates it](https://github.com/alhassy/org-special-block-extras/issues/17#issuecomment-1644865890).
