### ISSUE TITLE
Dependency from string library (s)  version 1.12.0 I believe its wrong 

### ISSUE THREAD

**Issue by azynheira** [alhassy/org-special-block-extras#14]
I have installed org-special-block-extras (both version 2 and the latest 20210806.154) and they state that one of their dependencies is s-1.12.0 as per (;; Package-Requires: ((s "1.12.0") (dash "2.18.0") (emacs "26.1") (org "9.1"))).

The problem here is they required a function called 's-replace-regexp' which is not present in version 1.12.0 (which I installed from MELPA-STABLE) but at least on the latest version in MELPA (20210616.619). That one worked for me.

This is not a huge issue but it needs to be stated somewhere that the correct version of the dependency.

**Comment by alhassy** [comment]
@azynheira Would you please make a pull request for the suggested change 😁

**Comment by azynheira** [comment]
Geez I totally forgot about this😁 Let me give it a try.

Pedro

**Comment by alhassy** [comment]
That sounds awesome; thank-you!

**Comment by alhassy** [comment]
@azynheira Thank-you for your efforts; this issue has now been resolved 🥳
