### ISSUE TITLE
Specifying column widths

### ISSUE THREAD

**Issue by makeartandgames** [alhassy/org-special-block-extras#19]
The site [under parallel](https://alhassy.github.io/org-special-block-extras/#Parallel) mentions defining percentage-width columns being possible.

Any thoughts on how that might be achieved, or might be "hacked in," even if I have to go and edit the HTML? I need 3 columns, with the middle column being much wider and the outside columns being much thinner--the effect would be something like a main text with commentaries on the side.

It's possible to hack this into CSS when there are just 2 columns (by making the first column very large) but I cannot find anyway to do it all with more than two.

**Comment by alhassy** [comment]
This issue has been addressed with commit 941553a9d6f232abba1584e72fde2f61c708cafb.
