### ISSUE TITLE
Support for dirlocal

### ISSUE THREAD

**Issue by seanfarley** [alhassy/org-special-block-extras#25]
This is a great package and I would love to use it with my collaborators! But in the current form, there needs to be some kind of "copy this config to your emacs." I think it would lower the adoption friction if this package could mark its own macros as safe so that we could check in a dirlocals file with all the shared macros.

**Comment by alhassy** [comment]
Hey @seanfarley, I'm glad you like the package.

> But in the current form, there needs to be some kind of "copy this config to your emacs."

Do you mean something like [this](https://github.com/alhassy/org-special-block-extras#installation-instructions)? If not, please elaborate.

> I think it would lower the adoption friction if this package could mark its own macros as safe so that we could check in a dirlocals file with all the shared macros.

Please elaborate, or give psuedo-code examples. I don't follow here.

**Comment by seanfarley** [comment]
> > But in the current form, there needs to be some kind of "copy this config to your emacs."
> 
> Do you mean something like [this](https://github.com/alhassy/org-special-block-extras#installation-instructions)? If not, please elaborate.

Righto, I mean defining `o-docs-libraries` in a project-specific way.

> > I think it would lower the adoption friction if this package could mark its own macros as safe so that we could check in a dirlocals file with all the shared macros.
> 
> Please elaborate, or give psuedo-code examples. I don't follow here.

Ah, I just meant having the ability to define `o-defblock` in `.dir-locals.el` so that we can check that into the repository. In this way, the only thing a collaborator will have to do is install this package. No extra configuration will be needed because the project defines and includes all the needed configuration.

**Comment by alhassy** [comment]
Okay, I'm still not following. 
1. Can you explain to me the problem you're having. (And so this PR would solve said problem).
2. Perhaps you can give me mock-usage and I'll be able to help.
3. Why would you want the _macro_ `o-defblock` in `.dir-locals.el`. It's a general macro, not really [specific for projects](https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html).

**Comment by seanfarley** [comment]
Ah, you're right, I haven't tried this and assumed something was different; apologies!

> Why would you want the macro o-defblock in .dir-locals.el. It's a general macro, not really [specific for projects](https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html).

From the example documentation, there is this code,

```lisp
;; We can use variable values when defining new blocks
(setq angry-red '(:foreground "red" :weight bold))

;; This is our 𝒳, “remark”.
;; As a link, it should be shown angry-red;
;; it takes two arguments: “color” and “signoff”
;; with default values being "red" and "".
(o-defblock rremark
  (editor "Editor Remark" :face angry-red) (color "red" signoff "")
  "Top level (HTML & LaTeX) editorial remarks; in Emacs they're angry red."
  (format (if (equal backend 'html)
            "<strong style=\"color: %s;\">⟦%s:  %s%s⟧</strong>"
            "{\\color{%s}\\bfseries %s:  %s%s}")
          color editor contents signoff))

;; I don't want to change the definition, but I'd like to have
;; the following as personalised defaults for the “remark” block.
;; OR, I'd like to set this for links, which do not have argument options.
(o-set-block-header-args rremark :main-arg "Jasim Jameson" :signoff "( Aim for success! )")
```

Once I check the example,

```org
The sum of the first $n$ natural numbers is $\sum_{i = 0}^n i = {n × (n + 1)
\over 2}$. Note that $n × (n + 1)$ is even.
[[rremark:Jasim Jameson][Why are you taking about “$\mathsf{even}$” here?]]
#+begin_rremark Bobbert Barakallah :signoff "Thank-you for pointing this out!" :color green
I was trying, uh ...

Yeah, to explain that ${\large n × (n + 1) \over 2}$ is always an integer.
#+end_rremark

Hence, we only need to speak about whole numbers.
[[rremark:][Then please improve your transition sentences.]]
```

into a repository, then other people that check out the code will not be able to export or preview the org document. Instead, they will receive the error `user-error: Unable to resolve link: "rremark:Jasim Jameson"`. I assumed `org-special-block-extras` could define `rremark` with variable (as opposed to macros) which is definitely my mistake. Since we need to run macros, we have to rely on `.dir-locals.el` having an `eval` like so,

```lisp
((nil . ((eval . (progn
                   (setq angry-red '(:foreground "red" :weight bold))
                   (org-special-block-extras-mode 1)
                   (o-defblock rremark
                               (editor "Editor Remark" :face angry-red) (color "red" signoff "")
                               "Top level (HTML & LaTeX) editorial remarks; in Emacs they're angry red."
                               (format (if (equal backend 'html)
                                           "<strong style=\"color: %s;\">⟦%s:  %s%s⟧</strong>"
                                         "{\\color{%s}\\bfseries %s:  %s%s}")
                                       color editor contents signoff))

                   ;; just to get the code to work; in practice, the project would probably not have a default
                   (o-set-block-header-args rremark :main-arg "Jasim Jameson" :signoff "( Aim for success! )"))))))
```

which definitely works after the user accepts the "do you trust this" prompt from emacs. So, this is not an issue at all and sorry for the noise 😬

**Comment by alhassy** [comment]
Thanks for confirming things work 😁 All the best!
