### ISSUE TITLE
Avoiding wrap with export block

### ISSUE THREAD

**Issue by bir000** [alhassy/org-special-block-extras#26]
Thanks for creating this wonderful package!

I have used org-defblock which returns a string I want to process more later. I export the buffer, and most times it just inserts the string like i expect. But if a line in the string starts with "* " it gets wrapped in an export block:
#+begin_export org/latex/html (depending on backend)
string
#+end_export

I see there is something in the docstring about an "ORG-EXPORT" function doing this, but I'm not good enough yet at elisp to figure out a way to control this behaviour. 

Any tips?

**Comment by alhassy** [comment]
This issue is stale and missing information; closing until more details are provided.

Please provide the definition of your defblock and how you use it and what you expect versues what you see; thank-you.
