### ISSUE TITLE
Some features not working together with `org-thtml`

### ISSUE THREAD

**Issue by MagicRB** [alhassy/org-special-block-extras#32]
Some parts, namely `((apply))`, spoilers and all blocks, are not working when going through  [org-thtml](https://github.com/juanjosegarciaripoll/org-thtml/). It's a niche, but really handy package IMO. I'd try to solve this myself, but my elisp skills don't go that far sadly.

**Comment by MagicRB** [comment]
I looked at the thtml code and it seems it should work, I'll test it more later.

**Comment by alhassy** [comment]
Unfortunately, with 2 kids and a full time job, and not being an active user of org-special-block-extras, this is not something I can direct immediate energy towards.

However, I'm happy to accept PRs and to help guide on making the changes, if you or someone else wants to champion this change.

**Comment by alhassy** [comment]
See also #35

**Comment by MagicRB** [comment]
I think i got the working, or thtml worked, but the org export blocks were for thtml not html. I'll post a snippet once I get home.

**Comment by alhassy** [comment]
This issue is stale and is apparently resolved. It would be nice to have the solution posted, @MagicRB 😉, so that knowledge could be shared in the offical docs.

Closing as there is nothing left to do (_on my side_).
