### ISSUE TITLE
Need help with making a block

### ISSUE THREAD

**Issue by rusimody** [alhassy/org-special-block-extras#34]
I want to have python snippets in org thus:
```
#+begin_PYT
def foo(x):
# Some python code
#+end_PYT
```

where `PYT` is a latex environment for python code using (say) listings.

It should expand to 

```
#+begin_export latex
\begin{PYT}
def foo(x):
# Some python code
\end{PYT}
#+end_export
```

Note 1. Python is just an example.  Actually I want this for multiple languages including one that's not in org babel's list.    
Note 2. A straight `#+begin_pyt` of course doesn't work because org transcodes (is that the word??) things like python's `[[2]]` into a link!!

I guess one should use `o-thread-blockcall` but I cant make out how!
Something like
```
(o-thread-blockcall 
   ('org-export-block 'latex-backend)
    'the-implied-block-begin-PYT)
```

**Comment by opensource-philosophy** [comment]
I am afraid I do not quite understand what you are up to, so I have a question of clarification: How would what you are up to differ from using a source code block like this?

``` org
#+BEGIN_SRC python :exports code
def print_pattern():
    size = 4
    for i in range(size):
        print("*" * size)
#+END_SRC
```
With `minted` (which is way better than `listings`), you would get

![image](https://user-images.githubusercontent.com/99628390/185696631-d0654fcc-0b17-47ea-99fa-515940cfe81c.png)

**Comment by rusimody** [comment]
> I am afraid I do not quite understand what you are up to, so I have a question of clarification: How would what you are up to differ from using a source code block like this?
> 
> ```
> #+BEGIN_SRC python :exports code
> def print_pattern():
>     size = 4
>     for i in range(size):
>         print("*" * size)
> #+END_SRC
> ```
> 
> With `minted` (which is way better than `listings`), you would get
> 
> ![image](https://user-images.githubusercontent.com/99628390/185696631-d0654fcc-0b17-47ea-99fa-515940cfe81c.png)

As I said:

> Python is just an example. Actually I want this for multiple languages including one that's not in org babel's list.

So

- I have a 'multi-lingual' (in programming languages sense) document
- Some of those languages have no org-babel entries. So `begin_src` cant be used here
- Actually it lies between between programming and math. See the math (not haskell) egs [here](https://tex.stackexchange.com/q/651092/53864)

PS. As for `minted` I gathered that listings can at least poorly produce proportional font, minted cant. minted is for color but my docs are mostly all for monochrome publications. If my understanding is wrong in this pls let me know!

**Comment by alhassy** [comment]
@rusimody I understand your problem, and the solution is as follows.

     Define the block:
     #+begin_src emacs-lisp
     (org-defblock PYT ()
       "Export to PYT blocks"
      (format "\\begin{PYT} %s \\end{PYT}" raw-contents))
     #+end_src
     
     #+begin_PYT
     def foo(x):
       # A Python comment I want exported
       # A Python nested list, [[2]], I want exported
     #+end_PYT
     
     Note that we need to use defblock here, since
     otherwise the Python comment “# ⋯” is interpreted
     as commented-out Org. Likewise Python nested lists
     =[[1]]= would be interpreted as links!
     
Any suggestions for improving the docs are welcome; including PRs or email me tip/idea; thanks.
