### ISSUE TITLE
No way to disable tooltips and the extraneous code in HTML export.

### ISSUE THREAD

**Issue by xaltsc** [alhassy/org-special-block-extras#36]
The minor mode's definition adds a lot of extra HTML code that, first, may not be needed by everyone using this package, second, loads stuff from foreign websites.

I'm not a security analyst, but I guess this could easily be considered a security threat, especially since it's the default behaviour of the package and the documentation doesn't especially warn the user that they will need untrusted data from an untrusted website.

**Comment by alhassy** [comment]
Thanks for noticing this issue and fixing it @xaltsc 🔥 

I think I will set your new variable to `t` by default, and will document to users your warnings.

That way, people opt-in by default but can also opt-out as desired.
