### ISSUE TITLE
Syntax highlighting in custom blocks are not working :(

### ISSUE THREAD

**Issue by barslmn** [alhassy/org-special-block-extras#41]
Thanks a lot for taking on this arduous task to bring such cool stuff. 

There were no mention to this in the manual or anything on the issues about highlighting. That's why I am opening this issue.

Latex blocks in column blocks:
![image](https://github.com/alhassy/org-special-block-extras/assets/43095157/dfc920d9-aa76-4390-b377-7a9f819722d9)

Code blocks in demo blocks:
![image](https://github.com/alhassy/org-special-block-extras/assets/43095157/8b301bcb-9837-4f06-82bf-c0f46b585224)

Is it possible to bring highligting back to special blocks?

Best, B

Versions:
GNU Emacs 28.2 (build 2, x86_64-pc-linux-gnu, X toolkit, cairo version 1.16.0, Xaw3d scroll bars) of 2023-05-14, modified by Debian
GNU Emacs     v28.2            nil
Doom core     v3.0.0-pre       HEAD -> master 07fca786 2023-05-30 19:39:04 -0400
Doom modules  v23.03.0-pre     HEAD -> master 07fca786 2023-05-30 19:39:04 -0400

Org mode version 9.6.1 (9.6.1-??-fe92a3ced @ /home/bar/.emacs.d/.local/straight/build-28.2/org/)

org-special-block-extras version 4.0.2

**Comment by alhassy** [comment]
Hey @barslmn, 

> Thanks a lot for taking on this arduous task to bring such cool stuff.

I'm glad to hear you like it :-)

> Is it possible to bring highligting back to special blocks?

It took some digging around, but I think I've got it. For now, all special blocks will be fontified as if they were "Org" language blocks. In the future, it'll probably be best to let the user decide how a block should be fontified.

Enjoy! 💐

**Comment by barslmn** [comment]
Hi Musa,

Just pulled the latest changes. It looks great 🥳. Thanks for your hardwork. 

![image](https://github.com/alhassy/org-special-block-extras/assets/43095157/d0723397-f632-4324-af28-c9299469f2c9)
