### ISSUE TITLE
Is there a listing for the necessary latex imports?

### ISSUE THREAD

**Issue by brittAnderson** [alhassy/org-special-block-extras#49]
Was trying out this package and wanted to test with a simple application of  the details block. My compilation to pdf failed unless I manually entered latex_header blocks for packages xcolor and tcolorbox. Do you have a concise listing of all the necessary latex packages that must be imported for the pre-written blocks you have to work? Thank you.

**Comment by alhassy** [comment]
I did a `M-s o \usepackage` search in the Org source. Here are the cleaned-up results:
```
\usepackage{newunicodechar}
\usepackage[hmargin=15mm,top=15mm,bottom=15mm]{geometry}
\usepackage{tcolorbox}
\usepackage{minted}
\usepackage{etoolbox}
\usepackage[dvipsnames]{xcolor} % named colours
\usepackage{multicol}
\usepackage{xcolor}
\usepackage{adjustbox}
```

Your issue suggests one improvement would be to have LaTeX tests for each block independently.
(Another improvement would be to have a concise listing of all required LaTeX packages in the README.)

**Comment by brittAnderson** [comment]
Much appreciated. Maybe enough for now to add to the readme near the installation instructions? Otherwise seems ready to close.
