### ISSUE TITLE
badge export fails with HTML special characters in URL...

### ISSUE THREAD

**Issue by psudopixel** [alhassy/org-special-block-extras#5]
a URL with a space in it (%20) fails to generate a badge.  really any % character in the URL causes the failure, the space is the easiest example to provide.

I'm not saying it's best practices, but Microsoft URLs for things in Sharepoint are riddled with them.

**Comment by alhassy** [comment]
Thanks for letting me know; I'll make a push to fix this soon :-)

**Comment by alhassy** [comment]
Fixed in most recent commit.
