### ISSUE TITLE
org-special-block-extras.el: Pattern t is deprecated.  Use `_' instead [2 times]

### ISSUE THREAD

**Issue by liebkne** [alhassy/org-special-block-extras#9]
Hi, 

I got this warning `../../.emacs.d/straight/build/org-special-block-extras/org-special-block-extras.el: Pattern t is deprecated.  Use `_' instead [2 times]` when loading `org-special-block-extras`. How can I get rid of this? Thanks!

**Comment by alhassy** [comment]
Thanks for the PR! ❤️
